service: mi-api-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true

functions:
  crearPersonaje:
    handler: handler.crearPersonaje
    events:
      - http:
          path: personajes/crear
          method: post

  obtenerPersonajes:
    handler: handler.obtenerPersonajes
    events:
      - http:
          path: personajes
          method: get

  helloperson:
    handler: handler.helloperson
    events:
      - http:
          path: hello/{name}
          method: get

  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user/create
          method: post

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/update/{id}
          method: put

resources:
  Resources:
    MiTablaDynamoDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PersonaDynamoDB
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
