service: api-prueba
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    PEOPLE_TABLE: "peolev2-dev"
  iam:
    role:
      statements:                  
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchWriteItem
        Resource:  
          - "arn:aws:dynamodb:us-east-1:381492172196:table/peolev2-dev"
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:BatchWriteItem
        Resource:                     
          - "arn:aws:dynamodb:us-east-1:381492172196:table/peolev2-dev/index/*"

functions:
  insertPeople:
    handler: functions/insert.crearPeopleHandler
    timeout: 25 # optional, in seconds, default is 6    
    memorySize: 2048 # Default memory size for functions (default: 1024MB)
    events:
      - http:
          path: /insert-people
          method: post
          cors: true
  getPeople:
    handler: functions/get.obtenerPeopleHandler
    events:
      - http:
          path: /get-people
          method: get
          cors: true
  getbyidPeople:
    handler: functions/get.obtenerPeopleIdHandler
    events:
      - http:
          path: /get-peopleid
          method: get
          cors: true

resources:
  Resources:
    maestroPeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: people-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST